workflows:
  version: 2
  main:
    jobs:
      - build:
          filters:
            branches:
              only: master

version: 2
jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:stretch
    environment:
      IMAGE_NAME: bambash/go-app
    steps:
      - checkout
      - run:
          name: Build application Docker image
          command: |
            docker build . -t $IMAGE_NAME:${CIRCLE_SHA1} -t $IMAGE_NAME:${CIRCLE_BRANCH} -t $IMAGE_NAME:latest
      - run:
          name: Run tests
          command: |
            echo 'uh oh... this example has no tests... shame on me.'
      - run:
          name: Push image
          command: |
            docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD
            docker push $IMAGE_NAME:${CIRCLE_SHA1}
            docker push $IMAGE_NAME:${CIRCLE_BRANCH}
            docker pu
